### ISSUE TITLE
Valid应在docall内再precheck一次

### ISSUE THREAD

**Issue by protectedMan** [feelschaotic/DelayAction#1]
Valid应在doCall内再preCheck一次
假设场景：未登录的用户先是addvalid到Call对象，然后通过其他途径登录。此时已经是登录态了。但是docall的时候没有检测登录态还是执行未登录的操作。

**Comment by feelschaotic** [comment]
你好，不需要在doCall内再preCheck一次。

以你的假设场景举例：未登录的用户点击关注按钮，先是addValid到Call对象，然后通过其他途径登录。此时已经是登录状态了。此时用户再次点击关注按钮，会**重新addValid**，此时检查到添加的Valid验证通过（已经通过其他途径登陆了），就**不会把这个Valid加入队列了**，所以此时会直接回调doCall，用户可以关注成功了。

虽然你提到doCall没有检测登录状态，但是此时的doCall已经不是第一次的doCall了，用户的操作会引起验证模型的更新。

**Comment by protectedMan** [comment]
是这样的，我的addvalid操作是在onCreate中执行的。
然后doCall是在一个按钮上进行调用的。
代码上的结构是这样的
![image](https://user-images.githubusercontent.com/17565737/54891519-9de63600-4ee8-11e9-8106-79e8c89b1f3d.png)

**Comment by feelschaotic** [comment]
非常不建议这么分离调用，因为这是个一体化的操作，用户的每次点击事件是互相独立的，所以应该
```
     findViewById(R.id.follow_btn).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                SingleCall.getInstance()
                        .addAction(new Action() {
                            @SuppressLint("WrongConstant")
                            @Override
                            public void call() {
                                Toast.makeText(MainActivity.this, "关注成功", Toast.LENGTH_SHORT).show();
                            }
                        })
                        .addValid(new LoginValid(MainActivity.this))
                        .doCall();
            }
        });
```
